### ISSUE TITLE
Resuming services: ya-runtime-sdk

### ISSUE THREAD

**Issue by mfranciszkiewicz** [golemfactory/ya-service-sdk#20]
Context: https://github.com/golemfactory/yagna/issues/1692#issuecomment-984107713

- rule of thumb: runtime process dies first

- runtime implementation ignores SIGTERM (so that only
  `RuntimeService::shutdown` is used for graceful termination)

- new: `Runtime::suspend`
  For implementing the snapshotting and halting mechanism.

  The expected behavior is to only snapshot the state when idle,
  i.e., when no ExeScript command is running. Running commands should
  be cancelled after a brief wait time period.

  Provides default implementation for serializing a basic state
  `struct` / `enum`, if set via `RuntimeDef` macro attribute.

- extend `ya-runtime-sdk-derive`'s `RuntimeDef` derive macro to
  set a custom state type and an option for disabling startup
  state auto-restoration

- restoration of the serialized state while starting the runtime,
  if the files can be found in the working directory (`workdir`)

**Comment by nieznanysprawiciel** [comment]
Not planned
