### ISSUE TITLE
release vm based on sdk

### ISSUE THREAD

**Issue by mateuszsrebrny** [golemfactory/ya-service-sdk#3]
Prerequisite: release `ya-runtime-sdk` to crates.io

**Comment by mfranciszkiewicz** [comment]
`ya-runtime-vm` PR: https://github.com/golemfactory/ya-runtime-vm/pull/89

awaits a crates.io release of `ya-runtime-sdk`

**Comment by tworec** [comment]
Deadline: 2021-05-24

**Comment by tworec** [comment]
Runtime VM is released
https://github.com/golemfactory/ya-runtime-vm/releases/tag/v0.2.7
