### ISSUE TITLE
Feature request: print macros

### ISSUE THREAD

**Issue by Wiezzel** [golemfactory/ya-service-sdk#8]
It's quite inconvenient for runtime developer to write something like this:
```rust
let stdout = format!(
    "Erigon available at: http://{}:8545",
    local_ipaddress::get().unwrap()
)
.as_bytes()
.to_vec();

emitter.command_stdout(0, stdout).await;
```
I'd love to have macros for printing to stdout/stderr that have a similar interface to `println`, e.g.:
```rust
yaprint!(
    emitter,
    "Erigon available at: http://{}:8545",
    local_ipaddress::get().unwrap()
)
```
Would that be difficult to add?

**Comment by mfranciszkiewicz** [comment]
@Wiezzel This macro is missing the command id parameter (`0`), which is important from the ExeUnit Supervisor's point of view. Adding it would make macro invocation less clean imo.

Could you take a look at my last PR and tell whether it improves output emission cumbersomeness? (#10)

https://github.com/golemfactory/ya-runtime-sdk/blob/mf/run-command/examples/example-runtime/src/main.rs#L49-L84

**Comment by Wiezzel** [comment]
@mfranciszkiewicz `run_ctx.stdout()` looks fine to me. :+1: You can close this issue once #10 gets merged.

**Comment by mfranciszkiewicz** [comment]
#10 is now merged into main
